[tool.black]
line-length = 160
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | Examples
  | pretrained_models
  | Testing
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.autopep8]
max_line_length = 160
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3

[tool.isort]
profile = "black"
line_length = 160
