[tool.black]
line-length = 160
target-version = ['py39']
include = '\.pyi?$'
exlude = '''
venv
Examples
pretrained_models
Testing
'''

[tool.autopep8]
max_line_length = 160
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3